version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeit}
    volumes:
       - ~/data/postgres/appsmith:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped

  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - 15433:80
  #   env_file:
  #     - .env
  #   depends_on:
  #     - database
  #   networks:
  #     - postgres-network
  #   volumes:
  #     - ./pgadmin-data/:/var/lib/pgadmin/